# Generated by Django 5.2.7 on 2025-10-21 16:44

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('welcome_heading', models.CharField(default='Welcome,', help_text='Main heading text at the top of the dashboard.', max_length=150)),
                ('intro_text', models.TextField(blank=True, default='Here’s an overview of your account and quick access to your saved items.', help_text='Displayed under the welcome heading on the dashboard.', null=True)),
                ('support_url', models.URLField(blank=True, help_text='Optional custom URL for the support/contact page. Defaults to /support/.', null=True)),
                ('left_title', models.CharField(default='Get In Touch', help_text='Title for the left box on the support page.', max_length=100)),
                ('response_time', models.CharField(default='Within 48 hours (weekdays)', help_text='Displayed response time.', max_length=100)),
                ('support_hours', models.CharField(default='Monday – Friday, 9AM – 4PM GMT', help_text='Displayed support hours.', max_length=100)),
                ('policies_link', models.URLField(blank=True, help_text='Optional link to policies index page.', null=True)),
                ('docs_link', models.URLField(blank=True, help_text='Optional link to documentation page.', null=True)),
                ('help_item_1', models.CharField(blank=True, max_length=120, null=True)),
                ('help_item_2', models.CharField(blank=True, max_length=120, null=True)),
                ('help_item_3', models.CharField(blank=True, max_length=120, null=True)),
                ('help_item_4', models.CharField(blank=True, max_length=120, null=True)),
                ('help_item_5', models.CharField(blank=True, max_length=120, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Dashboard Settings',
                'verbose_name_plural': 'Dashboard Settings',
            },
        ),
        migrations.CreateModel(
            name='HomePageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(default='Djangify', help_text='Displayed in the navbar next to the logo.', max_length=150, verbose_name='Business Name')),
                ('business_paragraph', models.TextField(blank=True, help_text='Old hero paragraph, now replaced by hero_paragraph. Safe to delete once migrated.', null=True, verbose_name='Deprecated – previously Hero Paragraph')),
                ('logo_image', models.ImageField(blank=True, help_text='Optional logo to display in the navbar beside the business name.', null=True, upload_to='homepage/logo/', verbose_name='Logo Image')),
                ('hero_title', models.CharField(default='Your Main Title', help_text='Main heading text displayed in the hero section.', max_length=150, verbose_name='Hero Title')),
                ('hero_paragraph', models.TextField(blank=True, help_text='Supporting 1–2 sentences displayed below the hero title.', null=True, verbose_name='Hero Paragraph')),
                ('hero_image', models.ImageField(blank=True, help_text='Optional hero background image (recommended 700×500px).', null=True, upload_to='homepage/hero/')),
                ('hero_button_text', models.CharField(blank=True, help_text="Optional button text for the hero area (e.g. 'Shop Now').", max_length=100, null=True)),
                ('hero_button_link', models.URLField(blank=True, help_text='Optional button link for the hero area (e.g. product or shop URL).', null=True)),
                ('social_1_name', models.CharField(blank=True, help_text='e.g. LinkedIn', max_length=50, null=True)),
                ('social_1_url', models.URLField(blank=True, null=True)),
                ('social_2_name', models.CharField(blank=True, help_text='e.g. Instagram', max_length=50, null=True)),
                ('social_2_url', models.URLField(blank=True, null=True)),
                ('copyright_text', models.CharField(blank=True, help_text='Optional custom copyright text. Leave blank to auto-generate.', max_length=200)),
                ('about_image', models.ImageField(blank=True, help_text='Upload a small logo image (max display size 128×128px)', null=True, upload_to='homepage/')),
                ('about_title', models.CharField(default='Your Title Here', max_length=150)),
                ('about_text', tinymce.models.HTMLField(help_text='Text for the About box section – around 70–100 words recommended.')),
                ('about_cta_text', models.CharField(blank=True, help_text='Optional small CTA below paragraph.', max_length=150, null=True)),
                ('about_cta_link', models.URLField(blank=True, null=True)),
                ('cta_title', models.CharField(default='Free Download: Title For Your Download', max_length=200)),
                ('cta_text', tinymce.models.HTMLField(blank=True, help_text='Intro text for the CTA box.', null=True)),
                ('cta_button_text', models.CharField(default='Here Is Your Download', max_length=100)),
                ('cta_button_link', models.URLField(blank=True, null=True)),
                ('cta_secondary_text', models.CharField(blank=True, default='Explore Our Shop', max_length=100)),
                ('cta_secondary_link', models.URLField(blank=True, null=True)),
                ('cta_image', models.ImageField(blank=True, null=True, upload_to='homepage/')),
                ('cta_pdf_upload', models.FileField(blank=True, null=True, upload_to='homepage/pdfs/')),
                ('blog_section_title', models.CharField(default='Latest Blog Posts', help_text='Displayed above the blog posts grid.', max_length=150)),
                ('blog_section_intro', models.TextField(blank=True, help_text='Short paragraph introducing the blog section (500 words or less).', max_length=500, null=True)),
                ('featured_products_title', models.CharField(default='Featured Products', max_length=150)),
                ('additional_products_title', models.CharField(default='More to Explore', max_length=150)),
                ('homepage_intro', models.TextField(blank=True, null=True)),
                ('announcement_bar_text', models.CharField(blank=True, max_length=200, null=True)),
                ('seo_meta_title', models.CharField(blank=True, max_length=150, null=True)),
                ('seo_meta_description', models.CharField(blank=True, max_length=255, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Home Page Settings',
                'verbose_name_plural': 'Home Page Settings',
            },
        ),
        migrations.CreateModel(
            name='SupportRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=150)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('handled', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
