# Generated by Django 5.2.7 on 2025-10-22 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagesettings',
            name='blog_section_intro',
            field=models.TextField(blank=True, help_text='Short paragraph introducing the blog section (700 words or less).', max_length=700, null=True),
        ),
    ]
