# Generated by Django 5.2.7 on 2025-10-22 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_homepagesettings_blog_section_intro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepagesettings',
            name='homepage_intro',
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='closing_text',
            field=models.TextField(blank=True, help_text='Optional text box shown after the download CTA at the bottom of the homepage.', null=True, verbose_name='Closing Text (End of Homepage)'),
        ),
    ]
