# Generated by Django 5.2.7 on 2025-10-22 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_homepagesettings_homepage_intro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagesettings',
            name='blog_section_title',
            field=models.CharField(blank=True, default='Latest Blog Posts', help_text='Displayed above the blog posts grid.', max_length=150, null=True),
        ),
    ]
