# Generated by Django 5.2.7 on 2025-10-22 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_homepagesettings_blog_section_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagesettings',
            name='about_title',
            field=models.CharField(blank=True, default='Your Title Here', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='additional_products_title',
            field=models.CharField(blank=True, default='More to Explore', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='cta_title',
            field=models.CharField(blank=True, default='Free Download: Title For Your Download', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='featured_products_title',
            field=models.CharField(blank=True, default='Featured Products', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='hero_title',
            field=models.CharField(blank=True, default='Your Main Title', help_text='Main heading text displayed in the hero section.', max_length=150, null=True, verbose_name='Hero Title'),
        ),
    ]
