# Generated by Django 5.2.7 on 2025-10-21 16:44

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InfoPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('slug', models.SlugField(help_text='Used in the page URL, e.g. /policies/terms/', unique=True)),
                ('page_type', models.CharField(choices=[('policy', 'Policy'), ('doc', 'Documentation')], max_length=10)),
                ('content', tinymce.models.HTMLField(help_text='Main page content. You can use headings, lists, and links.')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('published', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Info Page',
                'verbose_name_plural': 'Info Pages',
                'ordering': ['page_type', 'title'],
            },
        ),
    ]
