# Generated by Django 5.2.7 on 2025-11-04 17:13

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_product_files_alter_product_preview_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='files',
            field=models.FileField(blank=True, help_text='Upload a PDF or ZIP file. Use ZIP for bundles.', null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/media/secure/', location='C:\\Dev\\Projects\\zestizm\\media\\secure'), upload_to='products/files/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='preview_file',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/media/public/', location='C:\\Dev\\Projects\\zestizm\\media\\public'), upload_to='products/previews/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='preview_image',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/media/public/', location='C:\\Dev\\Projects\\zestizm\\media\\public'), upload_to='products/images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('download', 'Digital Download')], default='download', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='video_file',
            field=models.FileField(blank=True, help_text='Upload a short MP4 file to display as product video', null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/media/public/', location='C:\\Dev\\Projects\\zestizm\\media\\public'), upload_to='products/videos/'),
        ),
    ]
