# Generated by Django 5.2.7 on 2025-11-08 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_product_files_alter_product_preview_file_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GuestDetails',
        ),
    ]
